# Generated by Django 5.0.2 on 2024-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_parent_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
